# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10112beacfde28473e6cb49c93774364ef01dc17c6c03e3797184937e1475308eedcfdc57f260fc99f4250925ef16d2cac66b69926b06dbcaaebcc510dada25f

test:
  secret_key_base: 541286c2cae0fa6aae8598100e2c6867b944717191cbeb1091b11c3e3fe92d2ebec1422433d5ba991c437e0d4418fea2beb5d1c73f729ff0840e089aa603a19a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
